version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    restart: unless-stopped
    # Storage limits to prevent filling disk
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"